version: '3'

services:
  server:
    restart: always
    container_name: ark_server
    image: hermsi/ark-server:latest
    volumes:
      - /home/eero/ark-server-data:/app
      - /backup/ark-server-backups:/home/steam/ARK-Backups
    environment:
      - SESSION_NAME=testi
      - SERVER_MAP=TheIsland
      - SERVER_PASSWORD=$${{ secrets.SERVER_PASSWORD }}
      - ADMIN_PASSWORD=$${{secrets.ADMIN_PASSWORD }}
      - MAX_PLAYERS=10
      - UPDATE_ON_START=false
      - BACKUP_ON_STOP=false
      - PRE_UPDATE_BACKUP=true
      - WARN_ON_STOP=true
    ports:
      # Port for connections from ARK game client
      - "7777:7777/udp"
      # Raw UDP socket port (always Game client port +1)
      - "7778:7778/udp"
      # RCON management port
      - "27020:27020/tcp"
      # Steam's server-list port
      - "27015:27015/udp"
    networks:
      - default
